name: Build & Deploy Docs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Generate static docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run docs:generate
    - name: Upload generated docs
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: .output/public
        retention-days: 1
        
  deploy:
    name: Deploy generated docs
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download generated docs
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: docs
      - shell: bash
        run: |
          ls -la
          cat index.html
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz ./docs/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/docs.etherui.com
